### ISSUE TITLE
Delete this

### ISSUE THREAD

**Issue by letsgotomars** [npmdoc/node-npmdoc-quagga#1]

**Comment by kaizhu256** [comment]
hihi @serratus, i'm kai, the author of https://www.npmjs.com/~npmdoc (project to document the top 1% of all npm-packages).

i received a complaint from @letsgotomars to takedown the package https://www.npmjs.com/package/npmdoc-quagga

i've given you (@serratus, quagga's author), write access to https://www.npmjs.com/package/npmdoc-quagga so you can unpublish it if you feel strongly about it (but hopefully not ;)

cheers, and sincerely sorry for inconveniencing anyone, as npmdoc is intended to be a public service to document the many npm-packages that are lacking any documentation ^^;;;
